#!/bin/sh

down() {
brillo -u 150000 -U 10
brightness=$(light -g)
# dunstify -a "BRIGHTNESS" "$brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness_down.png -r 1 -u normal
notify-send -i ~/.config/dunst/assets/ui/brightness_down.png -h string:x-canonical-private-synchronous:sys-notify $brightness
}

up() {
brillo -u 150000 -A 10
brightness=$(light -g)
# dunstify -a "BRIGHTNESS" "$brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness_up.png -r 1 -u normal
notify-send -i ~/.config/dunst/assets/ui/brightness_up.png -h string:x-canonical-private-synchronous:sys-notify $brightness

}

case "$1" in
  up) up;;
  down) down;;
esac
